import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Toaster } from "sonner";
import { getMe } from "@/lib/getServerAuth";
import "@/styles/globals.css";
import "@/lib/logger";
import AuthProvider from "@/context/authContext";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const me = await getMe();
  console.log({ me });
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.variable} antialiased`}>
        <AuthProvider me={me}>
          {children}
          <Toaster
            position="top-right"
            theme="dark"
            richColors={true}
            expand={true}
            closeButton={true}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
