import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { getMe } from "@/lib/getServerAuth";
import AuthProvider from "@/context/AuthContext";
import "@/styles/globals.css";
import "@/lib/logger";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const me = await getMe();
  console.log({ me });
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <AuthProvider me={me}>
          {children}
          <Toaster position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
