import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/sonner";
import "@/setup/logger";
import { getServerAuth } from "@/lib/getServerAuth";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await getServerAuth();
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {children} <Toaster position="top-right" />
      </body>
    </html>
  );
}
